### ISSUE TITLE
Build_Routing_Stack problem with lake shapefile that intersection with domain is empty

### ISSUE THREAD

**Issue by shaimarvinblue** [NCAR/wrf_hydro_gis_preprocessor#13]
when using Build_Routing_Stack.py I use a hydroshed lakes shapefile. however in my domain there are no lakes. this triggered an error in the script and therefore I dont get the output zip file. when artificialy inserting a lake in the domain in the shape file the script work. the desired way of performing will be that I can insert an local lake shapefile and when I dont need to worry about wether there is a lake or not

**Comment by 0531-sudo** [comment]
I encountered the same problem. May I ask how to artificially insert a lake in the domain in the shape file?





    Adding auto-incremented lake ID field (1...n)
    Starting to gather lake centroid and area information.
    Done gathering lake centroid information.
    Found 145 lakes on active channels. Lost 5 lakes that were not on active channels.
    Removing lakes not on gridded channel network
    Process: LAKEGRID written to output netCDF.
Traceback (most recent call last):
  File "D:\APP\PyCharm 2024.1\PythonProject\CHJIANG\wrf_hydro_gis_preprocessor\wrf_hydro_gis_preprocessor\wrfhydro_gis\Build_Routing_Stack.py", line 544, in <module>
    GEOGRID_STANDALONE(args.in_Geogrid,
  File "D:\APP\PyCharm 2024.1\PythonProject\CHJIANG\wrf_hydro_gis_preprocessor\wrf_hydro_gis_preprocessor\wrfhydro_gis\Build_Routing_Stack.py", line 327, in GEOGRID_STANDALONE     
    rootgrp2, lake_ID_field = wrfh.add_reservoirs(rootgrp2,
  File "D:\APP\PyCharm 2024.1\PythonProject\CHJIANG\wrf_hydro_gis_preprocessor\wrf_hydro_gis_preprocessor\wrfhydro_gis\wrfhydro_functions.py", line 3125, in add_reservoirs
    flac_max = {lake:flac_arr[Lake_arr==lake].max() for lake in lake_uniques}
  File "D:\APP\PyCharm 2024.1\PythonProject\CHJIANG\wrf_hydro_gis_preprocessor\wrf_hydro_gis_preprocessor\wrfhydro_gis\wrfhydro_functions.py", line 3125, in <dictcomp>
    flac_max = {lake:flac_arr[Lake_arr==lake].max() for lake in lake_uniques}
  File "D:\APP\anaconda\envs\wrfh_gis_env\lib\site-packages\numpy\ma\core.py", line 6083, in max
    result = self.filled(fill_value).max(
  File "D:\APP\anaconda\envs\wrfh_gis_env\lib\site-packages\numpy\_core\_methods.py", line 44, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
